name: Build Podman Images

on:
  workflow_dispatch:
  push:
    branches:
    - legacy-centos
    tags:
      - 'v*.*.*'

jobs:
  BuildBase:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build base agent
        uses: ./.github/actions/build
        with:
          context: base
          dockerfile: base/podman/Dockerfile
          image-name: builder-base
          tag-suffix: -podman
          platforms: linux/amd64,linux/arm64
          docker-namespace: ${{ secrets.DOCKER_HUB_USER }}
          docker-password: ${{ secrets.DOCKER_HUB_SECRETS }}

  BuildMaven:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build maven agent
        uses: ./.github/actions/build
        with:
          context: maven
          dockerfile: maven/podman/Dockerfile
          image-name: builder-maven
          tag-suffix: -podman
          platforms: linux/amd64,linux/arm64
          docker-namespace: ${{ secrets.DOCKER_HUB_USER }}
          docker-password: ${{ secrets.DOCKER_HUB_SECRETS }}

  BuildNodejs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build nodejs agent
        uses: ./.github/actions/build
        with:
          context: nodejs
          dockerfile: nodejs/podman/Dockerfile
          image-name: builder-nodejs
          tag-suffix: -podman
          platforms: linux/amd64,linux/arm64
          docker-namespace: ${{ secrets.DOCKER_HUB_USER }}
          docker-password: ${{ secrets.DOCKER_HUB_SECRETS }}


