name: Build Podman Images

on:
  push:
    branches:
    - master
    - test-* # make it be easier for contributors to test
    tags:
      - 'v*.*.*'
  pull_request:
    branches:
      - 'master'

jobs:
  BuildBase:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Build base agent
        uses: ./.github/actions/build
        with:
          context: base
          dockerfile: base/podman/Dockerfile
          image-name: builder-base
          tag-suffix: -podman
          platforms: linux/amd64,linux/arm64
          docker-namespace: ${{ secrets.DOCKER_HUB_USER }}
          docker-password: ${{ secrets.DOCKER_HUB_SECRETS }}
          ghcr-token: ${{ secrets.GHCR_TOKEN }}

  BuildGo:
    needs: BuildBase
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Build Go agent
      uses: ./.github/actions/build
      with:
        context: go
        dockerfile: go/podman/Dockerfile
        image-name: builder-go
        tag-suffix: -podman
        platforms: linux/amd64,linux/arm64
        docker-namespace: ${{ secrets.DOCKER_HUB_USER }}
        docker-password: ${{ secrets.DOCKER_HUB_SECRETS }}
        ghcr-token: ${{ secrets.GHCR_TOKEN }}
        build-args: "GOLANG_VERSION=1.12.10"
  BuildGo16:
    needs: BuildBase
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Build Go 1.16 agent
      uses: ./.github/actions/build
      with:
        context: go
        dockerfile: go/podman/Dockerfile
        image-name: builder-go
        tag-suffix: -1.16-podman
        platforms: linux/amd64,linux/arm64
        docker-namespace: ${{ secrets.DOCKER_HUB_USER }}
        docker-password: ${{ secrets.DOCKER_HUB_SECRETS }}
        ghcr-token: ${{ secrets.GHCR_TOKEN }}
        build-args: "GOLANG_VERSION=1.16.8"
  BuildGo17:
    needs: BuildBase
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Build Go 1.17 agent
      uses: ./.github/actions/build
      with:
        context: go
        dockerfile: go/podman/Dockerfile
        image-name: builder-go
        tag-suffix: -1.17-podman
        platforms: linux/amd64,linux/arm64
        docker-namespace: ${{ secrets.DOCKER_HUB_USER }}
        docker-password: ${{ secrets.DOCKER_HUB_SECRETS }}
        ghcr-token: ${{ secrets.GHCR_TOKEN }}
        build-args: "GOLANG_VERSION=1.17.8"
  BuildGo18:
    needs: BuildBase
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Build Go 1.18 agent
      uses: ./.github/actions/build
      with:
        context: go
        dockerfile: go/podman/Dockerfile
        image-name: builder-go
        tag-suffix: -1.18-podman
        platforms: linux/amd64,linux/arm64
        docker-namespace: ${{ secrets.DOCKER_HUB_USER }}
        docker-password: ${{ secrets.DOCKER_HUB_SECRETS }}
        ghcr-token: ${{ secrets.GHCR_TOKEN }}
        build-args: "GOLANG_VERSION=1.18"

  BuildMaven:
    needs: BuildBase
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Build maven agent
      uses: ./.github/actions/build
      with:
        context: maven
        dockerfile: maven/podman/Dockerfile
        image-name: builder-maven
        tag-suffix: -podman
        platforms: linux/amd64,linux/arm64
        docker-namespace: ${{ secrets.DOCKER_HUB_USER }}
        docker-password: ${{ secrets.DOCKER_HUB_SECRETS }}
        ghcr-token: ${{ secrets.GHCR_TOKEN }}
        build-args: "JDK_VERSION=1.8.0"
  BuildMavenJDK11:
    needs: BuildBase
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Build maven(JDK11) agent
      uses: ./.github/actions/build
      with:
        context: maven
        dockerfile: maven/podman/Dockerfile
        image-name: builder-maven
        tag-suffix: -jdk11-podman
        platforms: linux/amd64,linux/arm64
        docker-namespace: ${{ secrets.DOCKER_HUB_USER }}
        docker-password: ${{ secrets.DOCKER_HUB_SECRETS }}
        ghcr-token: ${{ secrets.GHCR_TOKEN }}
        build-args: "JDK_VERSION=11"

  BuildMavenJDK17:
    needs: BuildBase
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Build maven(JDK17) agent
        uses: ./.github/actions/build
        with:
          context: maven
          dockerfile: maven/podman/Dockerfile
          image-name: builder-maven
          tag-suffix: -jdk17-podman
          platforms: linux/amd64,linux/arm64
          docker-namespace: ${{ secrets.DOCKER_HUB_USER }}
          docker-password: ${{ secrets.DOCKER_HUB_SECRETS }}
          ghcr-token: ${{ secrets.GHCR_TOKEN }}
          build-args: |
            "JDK_VERSION=17"
            "JDK_HOME=/usr/java/default"

  BuildGradle:
    needs: BuildBase
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Build Gradle agent
      uses: ./.github/actions/build
      with:
        context: gradle
        dockerfile: gradle/podman/Dockerfile
        image-name: builder-gradle
        tag-suffix: -podman
        platforms: linux/amd64,linux/arm64
        docker-namespace: ${{ secrets.DOCKER_HUB_USER }}
        docker-password: ${{ secrets.DOCKER_HUB_SECRETS }}
        ghcr-token: ${{ secrets.GHCR_TOKEN }}

  BuildNodeJs:
    needs: BuildBase
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Build NodeJS agent
      uses: ./.github/actions/build
      with:
        context: nodejs
        dockerfile: nodejs/podman/Dockerfile
        image-name: builder-nodejs
        tag-suffix: -podman
        platforms: linux/amd64,linux/arm64
        docker-namespace: ${{ secrets.DOCKER_HUB_USER }}
        docker-password: ${{ secrets.DOCKER_HUB_SECRETS }}
        ghcr-token: ${{ secrets.GHCR_TOKEN }}

  BuildPython:
    needs: BuildBase
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Build Python agent
      uses: ./.github/actions/build
      with:
        context: python
        dockerfile: python/podman/Dockerfile
        image-name: builder-python
        tag-suffix: -podman
        platforms: linux/amd64,linux/arm64
        docker-namespace: ${{ secrets.DOCKER_HUB_USER }}
        docker-password: ${{ secrets.DOCKER_HUB_SECRETS }}
        ghcr-token: ${{ secrets.GHCR_TOKEN }}
