name: Docker Image Dev

on:
  push:
    branches:
    - master
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build Image
      run: |
        tag=latest
        docker build base --file base/Dockerfile --tag kubespheredev/builder-base:$tag
        docker build go --file go/Dockerfile --tag kubespheredev/builder-go:$tag
        docker build maven --file maven/Dockerfile --tag kubespheredev/builder-maven:$tag
        docker build nodejs --file nodejs/Dockerfile --tag kubespheredev/builder-nodejs:$tag
    - name: Publish Image
      if: github.ref == 'refs/heads/master'
      run: |
        docker login -u ${{ secrets.DOCKER_HUB_USER }} -p ${{ secrets.DOCKER_HUB_SECRETS }}
        tag=latest
        docker push kubespheredev/builder-base:$tag
        docker push kubespheredev/builder-go:$tag
        docker push kubespheredev/builder-maven:$tag
        docker push kubespheredev/builder-nodejs:$tag